version: '3'

services:
  node:
    build: .
    container_name: node
    ports:
      - "3000:3000"
    environment:
      DB_HOST: databases
      DB_USER: databases
      DB_PASSWORD: databases
      DB_NAME: databases
    depends_on:
        databases:
          condition: service_healthy
    command: npm start
    networks:
      - app_network


  databases:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_USER: databases
      MYSQL_PASSWORD: databases
      MYSQL_ROOT_PASSWORD: databases
      MYSQL_DATABASE: databases
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - app_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9080:80"
    environment:
      PMA_HOST: databases
      MYSQL_ROOT_PASSWORD: databases
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
