version: '3.7'

services:
  app:
    build: .
    environment:
      - DB_HOST=database
      - DB_NAME=database
      - DB_USER=database
      - DB_PASSWORD=database
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mynetwork
  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
      MYSQL_ROOT_PASSWORD: database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "6000:6000"
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 6000
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - mynetwork
    

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge