version: '3.7'

services:
  app:
    build: .
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_NAME=database
      - DB_USER=database
      - DB_PASSWORD=database
    ports:
      - "5000:5000"





