version: '3.7'

services:
  app:
    build: .
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - DB_NAME=database
      - DB_USER=database
      - DB_PASSWORD=database
    ports:
      - "4000:4000"
