name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'mydatabase' # Optional, default value is "test". The specified database which will be create
        mysql root password:  ${{ secrets.DB_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: ${{ secrets.DB_USER }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password:  ${{ secrets.DB_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
    - name: Build the Docker image
      env:
        PORT: ${{ secrets.PORT }}
        DB_NAME: mydatabase
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        PMA_HOST: ${{ secrets.PMA_HOST }}
        PMA_PORT: ${{ secrets.PMA_PORT }}
        UPLOAD_LIMIT: ${{ secrets.UPLOAD_LIMIT }}
      run: printenv  && docker-compose up -d 
    - name: Debug
      run: printenv
    - name: Show app log
      run: docker ps && docker logs -f docker_test_nodejs_workflow_app_1 
    - name: Run tests in the Docker container
      run: docker exec docker_test_nodejs_workflow_app_1   bash -c "npm test"


