name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
            mysql:
                image: mysql:8
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping"
                         --health-interval=5s
                         --health-timeout=2s
                         --health-retries=3
                env:
                  MYSQL_DATABASE: database
                  MYSQL_USER: database
                  MYSQL_PASSWORD: database
                  MYSQL_ROOT_PASSWORD: database
    steps:
    - uses: actions/checkout@v3
    - name: Get MySQL service ID
      id: mysql-service
      run: container-id=$(docker ps | grep -i mysql | awk '{print $1}')
    - name: Get Github network gateway address
      id: github-network
      run: echo docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' ${{ steps.mysql-service.outputs.container-id }}
    - name: Build the Docker image
      run: printenv  && docker-compose up -d
    - name: Debug
      run: printenv
    - name: Show app log
      run: docker ps && docker logs -f docker_test_nodejs_workflow_app_1 
    - name: Run tests in the Docker container
      run: docker exec docker_test_nodejs_workflow_app_1   bash -c "npm test"


