name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env: 
        DB_HOST: ""
    services:
            mysql:
                image: mysql:8
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping"
                         --health-interval=5s
                         --health-timeout=2s
                         --health-retries=3
                env:
                  MYSQL_DATABASE: databases
                  MYSQL_USER: databases
                  MYSQL_PASSWORD: databases
                  MYSQL_ROOT_PASSWORD: databases
    steps:
    - uses: actions/checkout@v3
    - name: Get Github network gateway address
      id: github-network
      run: docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' $(docker ps | grep -i mysql | awk '{print $1}')
    - name: set env
      run: export MYSQL_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' $(docker ps | grep -i mysql | awk '{print $1}'))
           && echo "MYSQL_HOST=$MYSQL_HOST" >> $GITHUB_ENV
    - name: Build the Docker image
      run: printenv  && docker build --tag node_back:latest .
    - name: Run the container
      run: docker run -d --env MYSQL_HOST=$MYSQL_HOST --env DB_NAME=$MYSQL_DATABASE --env DB_USER=$MYSQL_USER --env DB_PASSWORD=$MYSQL_PASSWORD --env MYSQL_PORT=32768 --name node_back_end node_back:latest
    - name: Debug
      run: printenv
    - name: Show app log
      run: docker ps && docker logs node_back_end 
    - name: Run tests in the Docker container
      run: docker exec node_back_end   bash -c "npm test"


