name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
            mysql:
                image: mysql:8
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping"
                         --health-interval=5s
                         --health-timeout=2s
                         --health-retries=3
                env:
                  MYSQL_DATABASE: database
                  MYSQL_USER: database
                  MYSQL_PASSWORD: database
                  MYSQL_ROOT_PASSWORD: database
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        PORT: ${{ secrets.PORT }}
        PMA_HOST: ${{ secrets.PMA_HOST }}
        PMA_PORT: ${{ secrets.PMA_PORT }}
        UPLOAD_LIMIT: ${{ secrets.UPLOAD_LIMIT }}
      run: printenv  && docker-compose up -d 
    - name: Debug
      run: printenv
    - name: Show app log
      run: docker ps && docker logs -f docker_test_nodejs_workflow_app_1 
    - name: Run tests in the Docker container
      run: docker exec docker_test_nodejs_workflow_app_1   bash -c "npm test"


