name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        PORT: ${{ secrets.PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        PMA_HOST: ${{ secrets.PMA_HOST }}
        PMA_PORT: ${{ secrets.PMA_PORT }}
        UPLOAD_LIMIT: ${{ secrets.UPLOAD_LIMIT }}
      run: printenv  && docker-compose up -d && docker-compose exec docker_test_nodejs_workflow_app_1  env | grep DB_PASSWORD
    - name: Debug
      run: printenv
    - name: Show app log
      run: docker ps && docker logs -f docker_test_nodejs_workflow_app_1 
    - name: Run tests in the Docker container
      run: docker exec docker_test_nodejs_workflow_app_1   bash -c "npm test"


