name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        PORT: ${{ secrets.PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        PMA_HOST: ${{ secrets.PMA_HOST }}
        PMA_PORT: ${{ secrets.PMA_PORT. }}
        UPLOAD_LIMIT: ${{ secrets.UPLOAD_LIMIT }}
      run: docker-compose up -d
    - name: Run tests in the Docker container
      run: docker exec nodejs_test_docker-app-1 bash -c "npm test"

