name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      app:
        image: docker-demon-node
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t docker-demon-node .
      - name: Start app
        run: docker run -d -p 5000:5000 docker-demon-node
      - name: Wait for app to start
        run: |
          n=0
          until [ $n -ge 10 ] || $(curl --head --fail http://localhost:3000); do
            n=$[$n+1]
            sleep 10
          done
      - name: Run tests
        run: docker exec -it docker-image-name npm test
